### ISSUE TITLE
[Epic] Docker regestry 

### ISSUE THREAD

**Issue by mathijsglazema** [murunu/FAAS#11]
### Description

As Developer i want to make a docker regestry in our Kubernetes cluster so we can save the images of the docker containers. 

### Stories
- [ ] #12
- [ ] #13
- [ ] #14
- [ ] #15
- [ ] #16
- [ ] #17
---
### ToDoPersonal
- [ ] #18
---
### Criteria 
- [ ] Can push image to regesry
- [ ] Multi  tennant Only acces your only own Images
- [ ]  Can backup to Minio
- [ ]  Able to be pulled Own c# application
